color: indigo
fieldLayouts:
  97d4ba25-67bf-4011-a570-89dc7968f504:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae099328-696c-4aec-ba0d-d681708703d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bcb4d2b-6a3b-4c37-9383-55bb1ee5417e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b56a3e13-5350-4669-92f4-3c1252afd4a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c504c47-bbf2-4636-9255-4be38de73690
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89c1d851-c9a0-4fe5-bb08-c5aef4591b3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3710a5c7-fa54-4a2c-a07b-4f7a31f5bd25 # Background Repeat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62a8b06e-b7ba-4d8d-be65-729039e24db7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81cc92d-9e5b-440d-8461-cdf9ab64807e # Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 406991c6-50fe-44fe-b4f2-0f938f689962
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ee63b61-ea03-4a77-8d56-3a9a225b6da4
        userCondition: null
handle: background
hasTitleField: true
icon: image-polaroid
name: Background
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
