color: lime
fieldLayouts:
  1f5b8072-a4f6-4e9c-96c8-42fd1d85e322:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e9ad5662-9537-4ace-b3cd-0d41a2558649
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 936b666e-ee7b-492d-b3ae-8490b5597276
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0306909a-922b-4bf4-a624-87a9539e833d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78b7e7f5-933b-4ef9-87d1-dd81cad4d0e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aab24cd7-9f55-4b79-9b93-9fbac9f58fea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5add3acb-48ba-4f05-a381-8699db781713
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: dd9772a9-92b7-4017-a3eb-82715b3b2249
        userCondition: null
handle: column
hasTitleField: true
icon: table-columns
name: 'Layout Column'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
