color: lime
fieldLayouts:
  602761bd-0558-4ccc-9ed4-25035ccc88d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7dd38a2f-a68f-4f4f-af10-d2874e8aad21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa0fd04-151f-4094-a7d2-0a689296d2f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a18837ef-f239-47ad-b80a-5ec134c43f02
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4dbe62f4-8253-43b4-9cda-058e34d922c8 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a87939dc-2dbd-468e-b22e-5141b863c53d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6fc9e05e-93e3-4b45-8288-201151e8b6e4 # Background Imagery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e927fb81-86f4-4065-9659-8474e0fdd022
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: 832bf520-e2e4-4bfc-985b-0959c3b38e46
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: Padding
            type: craft\fieldlayoutelements\Heading
            uid: bd13538e-09f1-47e6-bda7-bd399261d2de
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pt
            includeInCards: false
            instructions: null
            label: 'Top Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fa6cd95-5ed3-4c33-8fb5-9828ee184a12
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pb
            includeInCards: false
            instructions: null
            label: 'Bottom Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6189bbfd-46d6-4355-820e-8e3496dee27b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: px
            includeInCards: false
            instructions: null
            label: 'Gutter Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06b2362b-9f3d-4bfc-bb54-34b3b8b086f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Margins
            type: craft\fieldlayoutelements\Heading
            uid: c35620a0-be23-41a2-9866-eddfb40ec8ca
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8094b7ec-e5d2-44ff-aba5-d899cf3956d0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30a69a99-ff76-415c-96c6-8803d0632a2f
            userCondition: null
            warning: null
            width: 100
        name: Spacing
        uid: 9451ca2f-7420-40f7-8a60-0b0f05765b6e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d6e1e93-38ca-405d-a935-f5c62bdbbd8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d984080-00be-4234-a6a2-c62e0226bd6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d72450-b609-4046-a6e7-d48fb9de6841
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3cc35afe-af1b-4ee8-aa89-d2d5c11e61b9
        userCondition: null
handle: contentWrapper
hasTitleField: true
icon: candy
name: 'Content Wrapper'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
