color: lime
fieldLayouts:
  602761bd-0558-4ccc-9ed4-25035ccc88d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7dd38a2f-a68f-4f4f-af10-d2874e8aad21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa0fd04-151f-4094-a7d2-0a689296d2f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a18837ef-f239-47ad-b80a-5ec134c43f02
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Mode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e7cdb7b-5cd0-4749-9df8-b821e70a7e5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4828bf4d-05a0-4a1c-a43b-4093be361a58
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 569d975f-7001-40dd-b088-6f9614f17e06 # Content Wrapper Style Adjustments
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46dd5dc5-b0d2-4df1-b558-2d8a33446209
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: b42c56c6-36d3-4ec4-9476-3e7154204af8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d6e1e93-38ca-405d-a935-f5c62bdbbd8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d984080-00be-4234-a6a2-c62e0226bd6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70d72450-b609-4046-a6e7-d48fb9de6841
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3cc35afe-af1b-4ee8-aa89-d2d5c11e61b9
        userCondition: null
handle: contentWrapper
hasTitleField: true
icon: candy
name: 'Content Wrapper'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
