color: yellow
fieldLayouts:
  05db9514-d611-48e5-aa08-85e2bfbfd7b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98dc6e85-08cb-4409-9553-024ebd9883dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f0c10f75-8d5e-43c0-83a1-2321c04a2ebd # Form to Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b70a6d37-506f-4fd9-92dd-500d4f7cef89
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86886d72-23a0-4ed6-ad37-cdbf282f55ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: Color
            type: craft\fieldlayoutelements\Heading
            uid: 3d52e7a8-a67f-434c-b5eb-47ce59d6bd6a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ed35e7c-6939-46ea-b885-6b8a0d79b5b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Button
            type: craft\fieldlayoutelements\Heading
            uid: 2a95d88e-e710-4127-88e6-ebe02ee57c5b
            userCondition: null
          -
            elementCondition: null
            fieldUid: 47acc143-9347-4976-bd50-02778ffeabf1 # Button Styles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74587eb4-c316-41d3-acd3-7289c4eb852f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: adca13f3-4ae5-49c5-83c4-cab3dd9f5ece # Button Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f3275b2-f0fa-4055-966f-f0ac23a07c7d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: btnColor
            includeInCards: false
            instructions: null
            label: 'Button Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2364078c-7f2a-419d-a6ac-c4151f6845ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Adjustments
            type: craft\fieldlayoutelements\Heading
            uid: c593e390-4dd7-44bc-9378-b2836a954967
            userCondition: null
          -
            elementCondition: null
            fieldUid: 23f01ca6-c4de-4346-a8a1-75a6b95d1f53 # Form Style Adjustments
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0e72ebc-4cb9-4b4e-a68f-a4add6519c59
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: 28211a06-91fd-4664-90f6-6815239a56db
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2facd2d-d982-461c-a150-23d18e24bf5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f00b5fda-2e1f-4cd3-9a3b-d2ab1324bdf2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d16fba8-fa27-4abc-8bc6-79e1ea6b4184
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 3e7f673b-53b9-493a-a1d1-b289567774c1
        userCondition: null
handle: form
hasTitleField: true
icon: clipboard
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
