color: cyan
fieldLayouts:
  c175c6e1-c81e-467f-baab-fe3052dc4e9f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a37ac36-861f-46b3-bb48-ca5fb2526d97
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00f30005-4f29-4c62-b0b6-3cdd8c790959
        userCondition: null
handle: image
hasTitleField: true
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
