color: yellow
fieldLayouts:
  7e5feb3c-e3b1-4d57-9fde-a887e3b8e079:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a2c58b5-7d58-498a-92d5-a2b9a211ef45
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 722b5556-ee9e-4e0c-8a0d-a0950a45018f
        userCondition: null
handle: modal
hasTitleField: true
icon: clone
name: Modal
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
