color: green
fieldLayouts:
  f56e9dfe-aa7a-414d-b39c-a744ad3313bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 65a47959-1b80-408c-976f-9984e3d6ebd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1877f372-f86f-43c7-ad2d-db751703dabb
        userCondition: null
handle: row
hasTitleField: true
icon: table-layout
name: 'Layout Row'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
