color: lime
fieldLayouts:
  fa6e25ce-c2c5-44bf-af5c-a82c459145b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ba7ef40-4462-4afe-9b2e-d12e71ae7223
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: mainPhoto
            includeInCards: false
            instructions: null
            label: 'Main Photo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f656522e-23f6-47f9-aab5-15280eeb92ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 732c729f-8dbb-4f01-a463-c163ddc13eab # Left Right
            handle: photoPosition
            includeInCards: false
            instructions: null
            label: 'Photo Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b1d1bae-0023-48e8-8f9c-eddf42589f68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ceecee1-0248-4ae3-a12a-c90171e5f42f # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d7b06ee-0853-4a63-b698-1647b1844a55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b3e248e3-6b5d-4c4a-afec-3c228b721887
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: fullscreen
            includeInCards: false
            instructions: null
            label: 'Full Screen Width?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c626548-19a0-4346-9f76-85402ecf9165
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Color
            type: craft\fieldlayoutelements\Heading
            uid: 44609db2-bb94-42e2-a4a5-9ba2c0754587
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5514a63a-0a23-42f9-9333-5576b0e95462 # Color Scheme
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 194d15f4-73f4-4cbb-9708-651709ca5699
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 487ec441-2218-43e8-8a96-652a0649e437 # Color Picker
            handle: bgColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4cdfd58-6796-4b56-b7b6-d14e334025f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Adjustments
            type: craft\fieldlayoutelements\Heading
            uid: aa5d81f2-5346-4bc6-9a97-f58aa835c494
            userCondition: null
          -
            elementCondition: null
            fieldUid: 554d8669-e659-48d2-a13d-a32598ca78cb # Side by Side Photo Style Adjustments
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 424de470-0aa0-48c1-b5f4-2b62df139b85
            userCondition: null
            warning: null
            width: 100
        name: Styling
        uid: 51ce697d-3ab4-46e0-b479-e81d6a66ae1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: animateReveal
            includeInCards: false
            instructions: null
            label: 'Animate Reveal?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 678e8a0e-9d36-4288-9e7a-26022314370b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: animateChildren
            includeInCards: false
            instructions: null
            label: 'Animate Child Blocks?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ea6add7-251d-4c7a-aa06-9ebb7c138834
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3f9e59c-e941-404e-8bc8-b4c57ff28d5c # YesNo - Yes
            handle: staggerAnimations
            includeInCards: false
            instructions: null
            label: 'Stagger Child Animations?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83b45e4c-6989-4cdf-b5cd-c70a589c9852
            userCondition: null
            warning: null
            width: 100
        name: Animation
        uid: 7d5f1938-386f-40b2-b8be-0245a0fa3c2d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aff5008f-7857-42a0-ac87-5a9960d400a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2c2fea1-6f49-419d-ae83-ebde726a60d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9626c35e-85b0-4106-bbbf-8e48c2f0ae71
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 19688c00-f44b-4f0e-b507-72b502a4c6ae
        userCondition: null
handle: sectionSidePhoto
hasTitleField: true
icon: id-card
name: 'Side by Side Photo Section'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
