color: pink
fieldLayouts:
  fcc6d8c1-886b-42fb-9ddf-0ffd017539d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9adb19ae-4823-4bc5-a655-7344b2945b58
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14c7c08b-787c-45d0-aa11-9178552c0eb3
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 481dc6bc-ef4f-43e7-adb7-1c6b4751973e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d71008-d495-42d2-a5df-81f135d5450f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aae9458-caa5-4593-a434-7ed66fcbdae7
            userCondition: null
            warning: null
            width: 50
        name: Margins
        uid: d5958ba1-d0a1-4a94-8f99-b99005f4d3ac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 206d3220-640b-4b20-a440-faaa801a11d9 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c3d9f7d-1df2-4f59-970f-28ab7b5dcbf0
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: 74819bcb-d5bc-4f58-9d32-edc07e8fe932
        userCondition: null
handle: styleAdjustmentForm
hasTitleField: false
icon: palette
name: 'Style Adjustment - Form'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
