color: pink
fieldLayouts:
  04bd435b-ac69-4f3c-b1a4-d3230a1d87bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 49a0f4f0-d2be-45f2-b235-14b1562ae915
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d723aca5-860b-4289-85fd-a82f81bdac9b
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 5fdfbc35-b050-4b4d-92f9-4d786a8319a8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'These control settings are applied to all of the accordions in the set at the device size(s) selected. You can override these settings on a per accordion basis in each accordion.'
            type: craft\fieldlayoutelements\Tip
            uid: 96ac73f6-dc29-4f7e-ad35-5a24f5a22fe7
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5feec917-01fb-4987-bd1a-c38c337de8cf # Font
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a35c643-0d56-41fe-86fa-f3463d302b5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba9877c7-223a-4c59-b461-4cf1a5068a34 # Font Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 071c25f1-536f-4bf8-affc-aaa024802733
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57eb287d-cdc2-4fba-8588-5dc66ff28c86 # Line Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c424a0-bab9-45a7-9a08-94e88c1ed2c3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37a64193-e3ef-4a2d-aa91-555b436b1d7d # Italic?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 466f61e9-1ae9-42aa-b5bd-bcc3e2c9fd59
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1dd9550-b7de-4c8d-ac15-30a80aef59ff # Text Case
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6d074b-aa4d-4b75-acc4-ff1d0ff4bfc0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a727c99-d7ce-4920-b1db-ce06d0647067 # Letter Spacing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 092070c5-fdc2-4814-b498-0071aed1a0d2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Alignment and Columns'
            type: craft\fieldlayoutelements\Heading
            uid: 205d1530-3439-4837-b8e9-dadc5f5c3305
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d95a350-fb34-496c-8c66-da3952eb4373 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a20a8d0-9eba-4e93-ab03-8080bf1bcfec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54321551-57ae-4812-8a1d-c491760d59ad # Multi-Column Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26e2852f-f0b1-47db-ba2b-dac29be1c964
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: a93bf4cd-a10e-4c27-a427-e7b0849f2f9a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Padding (Applied to each of the accordions in the set)'
            type: craft\fieldlayoutelements\Heading
            uid: 0fd6ecb3-c56a-40d7-b6ab-2e68df2c8717
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pt
            includeInCards: false
            instructions: null
            label: 'Top Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cde7eb7-2da9-4985-9705-348ce2580d42
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pb
            includeInCards: false
            instructions: null
            label: 'Bottom Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ff8360-c6b8-48a8-bdd5-1c27e66b02b8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pl
            includeInCards: false
            instructions: null
            label: 'Left Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f200437c-d835-4776-ba3c-bcb8e6850153
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pr
            includeInCards: false
            instructions: null
            label: 'Right Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e371f11-4f88-47e0-9c27-bde0f020b4c1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Margins (Applied to the tab set)'
            type: craft\fieldlayoutelements\Heading
            uid: bc224dd2-cb85-4fde-a952-e13d632a65f7
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7617a46-418d-4d8c-98cc-fbafcad9d5c3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: bm
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c5f6b5e-d968-4f6c-9082-a13e74b89a49
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 1480d618-8f2a-4114-8974-a8ae85ac7ed6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: hidden
            includeInCards: false
            instructions: null
            label: 'Hidden?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 999540eb-dab4-427b-9b78-f79baed68981
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: 4eaec2f5-7aa3-45b0-88a4-439c3f3b2a71
        userCondition: null
handle: styleAdjustmentAccordionSet
hasTitleField: false
icon: palette
name: 'Style Adjustment - Accordion Set'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
