color: pink
fieldLayouts:
  13eec936-7774-4f94-b8c6-624bd44dea73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f91be7e-fb4f-4962-89f0-413eee69d558
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6611e3d-1028-4446-a403-1bf16d9a3c03
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 29ad262a-8fc7-4670-b18f-41b80403be2c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5feec917-01fb-4987-bd1a-c38c337de8cf # Font
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa03ed5-8877-41f4-acd3-31e9958b9e78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba9877c7-223a-4c59-b461-4cf1a5068a34 # Font Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4775fe14-300d-46db-9d1a-26d7424d88ae
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57eb287d-cdc2-4fba-8588-5dc66ff28c86 # Line Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 220a90ce-ee44-45ea-9ba0-ecf0c427f01b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37a64193-e3ef-4a2d-aa91-555b436b1d7d # Italic?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ffd7b58-dcc2-4a6f-b5b8-b39a7ccb488b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1dd9550-b7de-4c8d-ac15-30a80aef59ff # Text Case
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d5df84b-48ca-4a1a-86ef-4fb418a9c246
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a727c99-d7ce-4920-b1db-ce06d0647067 # Letter Spacing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34242b4a-c106-4311-a3c5-a49001350883
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Alignment and Columns'
            type: craft\fieldlayoutelements\Heading
            uid: c28e855e-3bcc-4b83-a02a-8acd799444fd
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d95a350-fb34-496c-8c66-da3952eb4373 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9be64f36-b571-44d4-be4a-09368ff75bd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13531367-46d6-4c50-8ec6-9bb2a6ab5ab1 # Number of Columns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6eb23b1-c448-46e2-a224-a4b6b8fa1fc5
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 9a4fa5ec-8598-4a48-9460-f567ad3c9386
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pt
            includeInCards: false
            instructions: null
            label: 'Top Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4183cfe0-e56e-465d-aa73-e6b69e412024
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pb
            includeInCards: false
            instructions: null
            label: 'Bottom Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86b11292-d721-44d2-9d1b-df60019ce5b4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pl
            includeInCards: false
            instructions: null
            label: 'Left Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8c7e427-08df-46d2-b9ee-c4399b4580e4
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pr
            includeInCards: false
            instructions: null
            label: 'Right Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97abfecb-77d1-45c6-97de-8aa395454470
            userCondition: null
            warning: null
            width: 50
        name: Padding
        uid: 44cd6b61-ede8-411b-bc4f-99f309741cdb
        userCondition: null
handle: styleAdjustmentTabPanel
hasTitleField: false
icon: palette
name: 'Style Adjustment - Tab Panel'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
