color: pink
fieldLayouts:
  949be51f-5d2d-440e-afdc-db5d6b960c5e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3641f00d-d81b-4c7e-9e6e-8b5d6bad65cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbdb6ca1-3991-4ea5-9486-05e6b9838682
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 193581fe-787a-429f-8e55-6ddd54cf3ad6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc41b08d-5f5b-4463-a6b0-dfcb3871adf8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0efdd015-e8ed-4ca6-816b-358eed399149
            userCondition: null
            warning: null
            width: 50
        name: Margins
        uid: 26605f07-97d0-4f31-ab86-86903982fb28
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 206d3220-640b-4b20-a440-faaa801a11d9 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d5d62e9-0271-4946-9675-9bc0a759e37b
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: e3d0df54-bc67-4d97-99be-84ad378aff8a
        userCondition: null
handle: styleAdjustmentRepeaters
hasTitleField: false
icon: palette
name: 'Style Adjustment - Repeaters'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
