color: pink
fieldLayouts:
  1edc36ad-c4fd-47cf-82f6-51c634d2c5c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 960b919a-0c18-4ac4-b267-be9c75421f0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ff8b887-a9b3-4e58-869c-09eb60479a19
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: e246f98e-d91d-415d-ace3-28a5de31cdd5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5feec917-01fb-4987-bd1a-c38c337de8cf # Font
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca508947-99a3-4b84-afc9-ca3f1468a5c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba9877c7-223a-4c59-b461-4cf1a5068a34 # Font Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07d65273-631d-4f87-a3e8-2fa65345ba34
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57eb287d-cdc2-4fba-8588-5dc66ff28c86 # Line Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50a65181-7d41-4087-844f-9e7088bb84d6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37a64193-e3ef-4a2d-aa91-555b436b1d7d # Italic?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca08d53b-a423-4c6e-a02b-55066c77907d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1dd9550-b7de-4c8d-ac15-30a80aef59ff # Text Case
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f2e953a-d7ee-46b6-acb4-95573fa2819a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a727c99-d7ce-4920-b1db-ce06d0647067 # Letter Spacing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c092c83-46fa-49e6-ac71-76256619644c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Alignment and Çolumns'
            type: craft\fieldlayoutelements\Heading
            uid: 0a78c42b-a47f-41d7-a55d-2041a02230f4
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d95a350-fb34-496c-8c66-da3952eb4373 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804b43a4-f6b3-4091-9c25-b448d6cd5363
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54321551-57ae-4812-8a1d-c491760d59ad # Multi-Column Settings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be634435-ef5c-455f-bd43-e21f8c433a1a
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 8644cd1c-7cd1-4092-bb9e-ef3a2634fb49
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Padding (Spacing Inside the Block)'
            type: craft\fieldlayoutelements\Heading
            uid: 020e2b9d-66a6-49fd-93ca-6ed654690bcf
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pt
            includeInCards: false
            instructions: null
            label: 'Top Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34fb13bb-9405-4269-a989-66d6711f352e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pb
            includeInCards: false
            instructions: null
            label: 'Bottom Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff477627-a8c5-48b0-a7e2-c4fdda79525a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pl
            includeInCards: false
            instructions: null
            label: 'Left Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7afbbf0-a756-4090-9c10-fa182ed07f5e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pr
            includeInCards: false
            instructions: null
            label: 'Right Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ae29bb0-7082-40f1-aa7a-6895b0148588
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Margins (Spacing Between This Block and Others)'
            type: craft\fieldlayoutelements\Heading
            uid: c86a56fe-ac6d-4173-9845-4ec193dff073
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ab2afc1-674e-400f-8e33-b8f2a095ea17
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14d61c95-576b-406f-a35a-bbb48a92ce54
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: ml
            includeInCards: false
            instructions: null
            label: 'Left Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e58ac6b-e733-4093-9418-a6a0ddcadc5c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mr
            includeInCards: false
            instructions: null
            label: 'Right Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ff93a4b-2f40-4885-b787-61b9c25d5d8f
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 87101e24-2ff6-4887-a42d-9b52e270b45b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: hidden
            includeInCards: false
            instructions: null
            label: 'Hidden?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b0c57f9-96d4-4c8c-80b6-4c517c23bf8f
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: ed42507a-d28d-42b1-b3ff-0ff58d6f4352
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: bgImg
            includeInCards: false
            instructions: null
            label: 'Background Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f972ad8-f116-4122-aea1-a51535dbd089
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a15acb30-97c6-4f3b-a1ff-a18189c3f9f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
                  layoutElementUid: a15acb30-97c6-4f3b-a1ff-a18189c3f9f3
                  operator: in
                  uid: d3161e54-3b79-4610-a9d0-47b1c41786b3
                  values:
                    - auto
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3710a5c7-fa54-4a2c-a07b-4f7a31f5bd25 # Background Repeat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a61edc-c0c5-4b31-89fe-4be429db554b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
                  layoutElementUid: a15acb30-97c6-4f3b-a1ff-a18189c3f9f3
                  operator: in
                  uid: 7bfb3255-5cce-4976-8293-2a2b4cbb1abc
                  values:
                    - auto
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 402d59ca-ced6-4240-baf1-fc5eb9acd839
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81cc92d-9e5b-440d-8461-cdf9ab64807e # Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84507bde-0fda-4a8c-b3eb-e302e6206211
            userCondition: null
            warning: null
            width: 100
        name: Background
        uid: b095beb1-b0d7-4a13-b970-9eb29dff3bc8
        userCondition: null
handle: styleAdjustmentContentWrapper
hasTitleField: false
icon: palette
name: 'Style Adjustment - Content Wrapper'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
