color: pink
fieldLayouts:
  1e05767a-6ce7-419d-a01d-4d7d9df246a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 08f31612-baba-4816-bc54-e74dd54dd031
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c43d8bbe-46e5-4a9d-a418-8dce1fa598aa
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 7fa33a0a-a555-4a34-b717-8af36287d3b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7be67ae-a8e0-4570-87d8-f40aee791c23
            userCondition: null
            warning: null
            width: 100
        name: Sizing
        uid: c250ed4c-9513-4625-b664-6871a6d5c92f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4a0e763-c922-419b-bab1-0aa30f5a298f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aa95036-adc2-4039-83ee-5492469b5e4f
            userCondition: null
            warning: null
            width: 50
        name: Margins
        uid: 6ee1ddf7-dbd6-41a6-895b-40ea758964c4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 206d3220-640b-4b20-a440-faaa801a11d9 # Display
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07bb0c76-65c0-404d-aa2e-e1cd13650c5a
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: f7487de8-dcfd-4a9d-985b-f105bf97d35b
        userCondition: null
handle: styleAdjustmentSliderSet
hasTitleField: false
icon: palette
name: 'Style Adjustment - Slider Set'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
