color: pink
fieldLayouts:
  39a13eb0-8278-4023-9517-3cafb2ac9eb3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d057b8e7-5a68-4513-bfee-17d9f13d4fc0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: 'Select the device size(s) that these adjustments apply to.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2c8df5-6168-41d8-87e3-45114927a940
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 59826caa-951a-451d-81b5-a3477692cb3d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5feec917-01fb-4987-bd1a-c38c337de8cf # Font
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ac72de4-ad02-427d-8b05-a605006276bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba9877c7-223a-4c59-b461-4cf1a5068a34 # Font Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 746811ce-619e-43a9-b198-689f6b540cbb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57eb287d-cdc2-4fba-8588-5dc66ff28c86 # Line Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fdede46-d869-4541-b376-ed2433c6e36f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37a64193-e3ef-4a2d-aa91-555b436b1d7d # Italic?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ba72aa1-3dd8-4dfb-9c9c-18bb86d22b2f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1dd9550-b7de-4c8d-ac15-30a80aef59ff # Text Case
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdfa427f-3d95-4fe0-95fc-bd28c0a75020
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a727c99-d7ce-4920-b1db-ce06d0647067 # Letter Spacing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55d00a67-da44-4775-bdf3-a6173eb6decd
            userCondition: null
            warning: null
            width: 50
        name: Type
        uid: 1b7312f9-f8d7-4747-8556-b424b3ddc609
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: fullScreen
            includeInCards: false
            instructions: 'Turn this on to have the section content extend top the full width of the screen instead of being contained to a certain width on larger screens.'
            label: 'Full Screen Width?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce19fed-5f04-4dfa-9362-a0c5d1232f02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Padding (Spacing Inside the Section)'
            type: craft\fieldlayoutelements\Heading
            uid: 2507e461-bb9b-42b3-9a90-f469d1c67d51
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pt
            includeInCards: false
            instructions: null
            label: 'Top Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67ff198f-d99f-431c-9c45-3513bcfd0bdc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pb
            includeInCards: false
            instructions: null
            label: 'Bottom Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a6a9642-26de-403d-9bbb-473db73e46fe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pl
            includeInCards: false
            instructions: null
            label: 'Left Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8721f9db-7a76-455a-929f-fea61e911ee6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: pr
            includeInCards: false
            instructions: null
            label: 'Right Padding'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 403c3767-eb8a-4b0c-83a9-6c1c8ceab8ae
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Margins (Spacing Between This Section and Others)'
            type: craft\fieldlayoutelements\Heading
            uid: b52d231d-d671-4a7b-b43e-4aab9ceb7542
            userCondition: null
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad78cfbe-c553-414b-a520-bad73965d46a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad3dcfb7-9f10-4eb5-80c8-462cbaedaa0c
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: e48c592a-75ac-4b68-a295-73339b5697ea
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: hidden
            includeInCards: false
            instructions: 'Turn this switch on to hide this section at this device size'
            label: 'Hidden?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c06c5549-1a85-4675-ac22-ca0013556dee
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: b22a53c9-edb7-4718-a3f4-000ff1629cf4
        userCondition: null
      -
        elementCondition: null
        name: Color
        uid: be97d614-50ab-42f9-9965-8a6513e03059
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f1b466ce-fb41-471a-90d4-5d0fd23f346d # Image Asset
            handle: bgImg
            includeInCards: false
            instructions: 'Select the image to use as the background for this device size.'
            label: 'Background Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae0067df-6a51-45be-88a3-2d1d773bc5d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d7a8320-da54-4376-9e73-94c88aa4b365
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
                  layoutElementUid: 2d7a8320-da54-4376-9e73-94c88aa4b365
                  operator: in
                  uid: 168e5406-0835-487c-b7a9-cfadf7ff8ac6
                  values:
                    - auto
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3710a5c7-fa54-4a2c-a07b-4f7a31f5bd25 # Background Repeat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4d59460-2b8f-410a-a986-211ce135d6c7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: f4d725e6-48b8-4083-a921-ecc0925a0bff # Background Size
                  layoutElementUid: 2d7a8320-da54-4376-9e73-94c88aa4b365
                  operator: in
                  uid: 702b2e55-3898-4edb-bbdb-f9fc4f175470
                  values:
                    - auto
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 0fe2ca3f-eb30-4294-96a2-1154bd95e41e # Background Position
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d9df8e1-880a-410f-8fb4-5781a4bf0d5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81cc92d-9e5b-440d-8461-cdf9ab64807e # Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 235ad32d-8952-4ec3-8c9d-d31ee759762b
            userCondition: null
            warning: null
            width: 100
        name: Background
        uid: caea7fec-16c3-4eb9-a669-c9414e666623
        userCondition: null
handle: styleAdjustmentSection
hasTitleField: false
icon: palette
name: 'Style Adjustment - Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Section{object.owner.canonicalId}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
