color: pink
fieldLayouts:
  b43ec5fb-b448-4058-8f80-1ba672d19113:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c87dc0a-a32c-4676-9da3-131fa5f93fe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f182d27-ea6e-4a71-a3f8-5c9d0f147eed # Device Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f4f7a32-7a81-4a09-9efd-19b6d81c2910
            userCondition: null
            warning: null
            width: 100
        name: 'Device Size'
        uid: 37c09faf-c74a-43cc-878b-bc009e37125e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5feec917-01fb-4987-bd1a-c38c337de8cf # Font
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9008c5cb-73df-4532-9049-75d4fcc350db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba9877c7-223a-4c59-b461-4cf1a5068a34 # Font Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28caac6d-4b92-4b7d-8f9a-7d4c8aebe174
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 57eb287d-cdc2-4fba-8588-5dc66ff28c86 # Line Height
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30eb1a1b-1b6b-4f20-b524-23b4413568e8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37a64193-e3ef-4a2d-aa91-555b436b1d7d # Italic?
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5765f0ce-e368-421a-9d3e-5f3b6dbca847
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1dd9550-b7de-4c8d-ac15-30a80aef59ff # Text Case
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d83541b-43e5-4931-9f2a-973265e304d6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a727c99-d7ce-4920-b1db-ce06d0647067 # Letter Spacing
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 041875ec-9663-4d8d-957e-db36168f7e74
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Alignment and Columns'
            type: craft\fieldlayoutelements\Heading
            uid: dbc35e01-f06d-4cdf-a955-c29304f7cac8
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d95a350-fb34-496c-8c66-da3952eb4373 # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23eaae93-e3eb-45d2-bf5e-be5be94aad6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13531367-46d6-4c50-8ec6-9bb2a6ab5ab1 # Number of Columns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a17ec443-d8cd-4fd3-a42e-264501ecbcc4
            userCondition: null
            warning: null
            width: 100
        name: Type
        uid: 561f1320-f82b-4462-a696-a693fd141901
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mt
            includeInCards: false
            instructions: null
            label: 'Top Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 118ad0bd-a2bf-4ff4-b40d-f4f92462c86a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 91d05e51-ee38-4e73-af4c-ebed7e7572d3 # Spacing
            handle: mb
            includeInCards: false
            instructions: null
            label: 'Bottom Margin'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 607d6e9c-f63f-40a3-8c52-76021598b3bc
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 3b4c3983-43b9-4fb8-9ec6-9764ceb6aebf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a2da31ae-7341-4dd1-b245-5ee55d44cbc2 # Yes No
            handle: hidden
            includeInCards: false
            instructions: null
            label: 'Hidden?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cde3fbbb-fda2-430c-b084-b6cad44ad918
            userCondition: null
            warning: null
            width: 100
        name: Display
        uid: e79a48be-b26b-4e5f-9d1b-a5af68e3cd2c
        userCondition: null
handle: styleAdjustmentCta
hasTitleField: false
icon: palette
name: 'Style Adjustment - CTA'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-styles-{ object.deviceSize }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
