color: cyan
fieldLayouts:
  71835647-cf57-489c-bb5e-8658ff5e7d23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 494fff11-9b3e-4e85-816c-e03fa14dc07f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79d28a86-5f89-45cb-99a4-a97fa0992c73 # Video Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27223db6-c153-4aad-b3b8-c82b05e10f29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f72b724-e0a8-4044-a3aa-12255ade6ea1 # Basic Text with Search
            handle: videoCaption
            includeInCards: false
            instructions: null
            label: 'Video Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf4bb9b4-4a3b-41e0-a4ba-5c4a292b8cc8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dd13752-3b26-46ab-89e7-bb0c2426682f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b484609-7d28-4f55-990e-f5212885d922 # Custom ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e386c3e-2e39-48e9-8334-927fdab578db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5 # Custom Classes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75fffc23-d3e6-4e2a-8a7c-0e27db538c55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee64f702-a8f1-46ee-8dea-79f8ad82e25b # Custom Attributes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5da6bb7e-14ac-4d61-94ee-a85efbbcc2c2
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: f9972402-86f2-400d-9dc0-94b3ae2a58bd
        userCondition: null
handle: video
hasTitleField: true
icon: film
name: Video
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
