headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Main Content'
options:
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - createEntry
  - heading
  - style
  - fontSize
  - fontColor
  - fontFamily
  - mediaEmbed
  - insertImage
  - '|'
  - bold
  - italic
  - link
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - sourceEditing
