headingLevels: false
name: 'Main Content'
options:
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - createEntry
  - style
  - '|'
  - bold
  - italic
  - link
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - sourceEditing
