altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  cb819768-bdf2-44ba-b940-bbdc3882dbdc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f45e2e3d-56f4-4ae1-bf31-081782cacaa0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d55b8d5a-e539-494c-9e3a-bb5159b39410
        userCondition: null
fs: docs
handle: documents
name: Documents
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
