altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  591914db-0320-44b3-a9a0-93e9bcf625fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: af3bc33b-4d2b-40b7-a045-886ad6784711
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 736faa6d-3585-457e-a390-4e43f19b6820
        userCondition: null
fs: embeds
handle: embeds
name: Embeds
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
