columnSuffix: null
handle: accordionStyleAdjustments
instructions: null
name: 'Accordion Style Adjustments'
searchable: false
settings:
  createButtonLabel: 'Adjust Style'
  entryTypes:
    - 7ff3d23a-91a6-4110-a3b0-b131dd2c3ee3 # Style Adjustment - Accordion
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
