columnSuffix: null
handle: aspectRatio
instructions: null
name: 'Aspect Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Natural Dimensions'
        -
          - value
          - aspect-auto
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - aspect-square
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '16/9 (Video)'
        -
          - value
          - aspect-video
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4/3
        -
          - value
          - aspect-4/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/2
        -
          - value
          - aspect-3/2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/1
        -
          - value
          - aspect-3/1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2/1
        -
          - value
          - aspect-2/1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4/1
        -
          - value
          - aspect-4/1
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
