columnSuffix: null
handle: backgroundPosition
instructions: null
name: 'Background Position'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Top Left'
        -
          - value
          - bg-left-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - bg-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Right'
        -
          - value
          - bg-right-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - bg-left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - bg-center
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - bg-right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Left'
        -
          - value
          - bg-left-bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bg-bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Right'
        -
          - value
          - bg-right-bottom
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
