columnSuffix: null
handle: backgroundPosition
instructions: null
name: 'Background Position'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Left Top'
        -
          - value
          - left-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Left Bottom'
        -
          - value
          - left-bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Right Top'
        -
          - value
          - right-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Right Bottom'
        -
          - value
          - right-bottom
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
