columnSuffix: null
handle: backgroundSize
instructions: null
name: 'Background Size'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Cover
        -
          - value
          - cover
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Contain
        -
          - value
          - contain
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
