columnSuffix: null
handle: btnColor
instructions: null
name: 'Button Color'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - cssColour
          - ''
        -
          - default
          - '1'
  placeholderText: 'Select an option'
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Colours
