columnSuffix: null
handle: buttonStyles
instructions: null
name: 'Button Styles'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Standard Button'
        -
          - value
          - btn-standard
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Text Button'
        -
          - value
          - btn-text
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Text Button with Arrow'
        -
          - value
          - btn-text-arrow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
