columnSuffix: null
handle: cardsPerRow
instructions: 'By Default, card repeaters will display 1 card per row on the phone and 3 per row on all other device sizes. If you want to change that, you can specify the number of cards per row for different device sizes with this field. Add a row to the field and specify the sizes with the dropdowns.'
name: 'Cards Per Row'
searchable: false
settings:
  addRowLabel: 'Make an Adjustment'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Device Size'
            -
              - handle
              - deviceSize
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - All
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - 'Phone Horizontal and Above'
                    -
                      - value
                      - sm
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Tablet and Above'
                    -
                      - value
                      - md
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Laptop and Above'
                    -
                      - value
                      - lg
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Desktop and Above'
                    -
                      - value
                      - xl
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Hi Res'
                    -
                      - value
                      - 2xl
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Number of Cards'
            -
              - handle
              - numberOfCards
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '1'
                    -
                      - value
                      - '1'
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - '2'
                    -
                      - value
                      - '2'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '3'
                    -
                      - value
                      - '3'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '4'
                    -
                      - value
                      - '4'
                    -
                      - default
                      - false
  defaults: null
  maxRows: 6
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
