columnSuffix: null
handle: colorPicker
instructions: null
name: 'Color Picker'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - cssColour
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Transparent
        -
          - value
          - transparent
        -
          - cssColour
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - cssColour
          - FFF
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - black
        -
          - cssColour
          - '000'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Red
        -
          - value
          - red
        -
          - cssColour
          - FF0000
        -
          - default
          - ''
  placeholderText: 'Select an option'
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Colours
