columnSuffix: null
handle: color
instructions: null
name: Color
searchable: false
settings:
  default: null
  options:
    -
      __assoc__:
        -
          - label
          - Black
        -
          - color
          - '#000'
        -
          - default
          - ''
        -
          - class
          - black
    -
      __assoc__:
        -
          - label
          - White
        -
          - color
          - '#FFF'
        -
          - default
          - ''
        -
          - class
          - white
  palette: null
  setRandom: false
  useConfigFile: false
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
