columnSuffix: null
handle: columnVerticalAlignment
instructions: null
name: 'Column Vertical Alignment'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Match Heights'
        -
          - value
          - self-stretch
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - self-top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Middle
        -
          - value
          - self-middle
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - self-bottom
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
