columnSuffix: null
handle: columns
instructions: null
name: Columns
searchable: false
settings:
  createButtonLabel: 'Add Column'
  entryTypes:
    - b6075a2a-820f-44f0-857b-358c60cb2bcb # Layout Column
  includeTableView: false
  maxEntries: 5
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
