columnSuffix: null
handle: dateFormat
instructions: null
name: 'Date Format'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Full Text Month (January 1, 2022)'
        -
          - value
          - 'F d, Y'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Short Text Month (Jan. 1, 2022)'
        -
          - value
          - 'M. d, Y'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Slashes No Leading Zeroes (1/1/2022)'
        -
          - value
          - n/j/Y
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Slashes Leading Zeroes (01/01/2022)'
        -
          - value
          - m/d/Y
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Dashes No Leading Zeroes (1-1-2022)'
        -
          - value
          - n-j-Y
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Dashes Leading Zeroes (01-01-2022)'
        -
          - value
          - m-d-Y
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Dots No Leading Zeroes (1-1-2022)'
        -
          - value
          - n.y.Y
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Numeric Dots Leading Zeroes (01.01.2022)'
        -
          - value
          - m.d.Y
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
