columnSuffix: null
handle: font
instructions: null
name: Font
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'No Change'
        -
          - value
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
