columnSuffix: null
handle: headerBlock
instructions: null
name: 'Header Block'
searchable: false
settings:
  createButtonLabel: 'Create Header'
  entryTypes:
    - b1e1aad8-a87c-4914-9445-bbbbb92076ee # Heading
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
