columnSuffix: null
handle: iconStyleAdjustments
instructions: null
name: 'Icon Style Adjustments'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - d81788e7-2fa5-4804-876d-57de4924e46f # Style Adjustment - Icon
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
