columnSuffix: null
handle: icon
instructions: null
name: Icon
searchable: false
settings:
  iconSets: '*'
  renderId: null
  showLabels: true
translationKeyFormat: null
translationMethod: none
type: verbb\iconpicker\fields\IconPickerField
