columnSuffix: null
handle: leftRight
instructions: null
name: 'Left Right'
searchable: false
settings:
  default: false
  offLabel: Left
  onLabel: Right
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
