columnSuffix: null
handle: listOrder
instructions: null
name: 'List Order'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Newest to Oldest'
        -
          - value
          - dd
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Oldest to Newest'
        -
          - value
          - da
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Random
        -
          - value
          - r
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - A-Z
        -
          - value
          - az
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Z-A
        -
          - value
          - za
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Admin Defined (for entries that can be rearranged in the control panel)'
        -
          - value
          - cp
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
