columnSuffix: null
handle: numberOfColumns
instructions: null
name: 'Number of Columns'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '1'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
