columnSuffix: null
handle: repeaterDisplay
instructions: null
name: 'Repeater Display Type'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Simple Text List'
        -
          - value
          - textList
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Buttons
        -
          - value
          - buttonList
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Card
        -
          - value
          - cardList
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Card with Small Image'
        -
          - value
          - cardListSmallImage
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Card with Large Image'
        -
          - value
          - cardListLargeImage
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Large Slider'
        -
          - value
          - largeSlider
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Multi Card Slider'
        -
          - value
          - multiCardSlider
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
