columnSuffix: null
handle: rowLayout
instructions: 'Use this field to adjust the layout of the row from the default (centered columns with matching heights)'
name: 'Row Layout'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Device Size'
            -
              - handle
              - deviceSize
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - All
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - 'Phone Horizontal and Above'
                    -
                      - value
                      - sm
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Tablet and Above'
                    -
                      - value
                      - md
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Laptop and Above'
                    -
                      - value
                      - lg
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Desktop and Above'
                    -
                      - value
                      - xl
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Hi Res'
                    -
                      - value
                      - 2xl
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Horizontal Layout'
            -
              - handle
              - horizontalLayout
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Default (No Change)'
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Left
                    -
                      - value
                      - justify-start
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Right
                    -
                      - value
                      - justify-end
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Center
                    -
                      - value
                      - justify-center
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Spread Out'
                    -
                      - value
                      - justify-between
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'Even Spacing'
                    -
                      - value
                      - justify-evenly
                    -
                      - default
                      - false
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Vertical Layout'
            -
              - handle
              - verticalLayout
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Default (No Change)'
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - 'Match Heights'
                    -
                      - value
                      - items-stretch
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Top
                    -
                      - value
                      - items-start
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Middle
                    -
                      - value
                      - items-center
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Bottom
                    -
                      - value
                      - items-end
                    -
                      - default
                      - false
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
