columnSuffix: null
handle: rowMargins
instructions: null
name: 'Row Margins'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - optgroup
          - 'Scaling Sizes'
    -
      __assoc__:
        -
          - label
          - 'Negative Extra'
        -
          - value
          - neg-extra
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative Normal'
        -
          - value
          - neg-normal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - '0'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - value
          - normal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Extra
        -
          - value
          - extra
        -
          - default
          - ''
    -
      __assoc__:
        -
          - optgroup
          - 'Fixed Sizes'
    -
      __assoc__:
        -
          - label
          - 'Negative 4x'
        -
          - value
          - neg-4x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative 3x'
        -
          - value
          - neg-3x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative 2x'
        -
          - value
          - neg-2x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative Base'
        -
          - value
          - neg-base
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative Half'
        -
          - value
          - neg-half
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Negative Quarter'
        -
          - value
          - neg-quarter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Quarter
        -
          - value
          - quarter
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Half
        -
          - value
          - half
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Base
        -
          - value
          - base
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2x
        -
          - value
          - 2x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3x
        -
          - value
          - 3x
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4x
        -
          - value
          - 4x
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
