columnSuffix: null
handle: rowStyleAdjustments
instructions: null
name: 'Row Style Adjustments'
searchable: false
settings:
  createButtonLabel: 'Adjust Style'
  entryTypes:
    - 6f85f87f-2394-4346-8cc1-3c89dbc64756 # Style Adjustment - Row
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
