columnSuffix: null
handle: sliderSize
instructions: null
name: 'Slider Size'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 16/9'
        -
          - value
          - 16-9
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 4/3'
        -
          - value
          - 4-3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 3/2'
        -
          - value
          - 3-2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 3/1'
        -
          - value
          - 3-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - 1-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Natural
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
