columnSuffix: null
handle: sliderSize
instructions: 'This field sets the aspect ratio for the images in the slider on device sizes above phone size. Phone sizes are set to square dimensions intrinsically. All the sizes except for Natural crop the images. Natural uses the dimensions of the images themselves, so if all the images aren''t the same dimensions then the slider will change sizes when each slide transitions.'
name: 'Slider Size'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 16/9'
        -
          - value
          - video
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 4/3'
        -
          - value
          - 4/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 3/2'
        -
          - value
          - 3/2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Rectangle - 3/1'
        -
          - value
          - 3/1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Natural
        -
          - value
          - auto
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
