columnSuffix: null
handle: sliderSetStyleAdjustments
instructions: null
name: 'Slider Set Style Adjustments'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 60656df7-fedd-4651-ae29-cf30fdef7f08 # Style Adjustment - Slider Set
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
