columnSuffix: null
handle: slideStyleAdjustments
instructions: null
name: 'Slide Style Adjustments'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - d7b08a46-def6-44b3-9d7d-4ef745756fca # Style Adjustment - Slide
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
