columnSuffix: null
handle: slideTransitionDelay
instructions: null
name: 'Slide Transition Delay'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '5 Seconds'
        -
          - value
          - '5000'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '6 Seconds'
        -
          - value
          - '6000'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '7 Seconds'
        -
          - value
          - '7000'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '8 Seconds'
        -
          - value
          - '8000'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
