columnSuffix: null
handle: slideColumns
instructions: null
name: 'Slide Columns'
searchable: false
settings:
  createButtonLabel: 'Add Column'
  entryTypes:
    - 263e5dea-ef08-42a5-8e17-6418ad4de62b # Slide Column
  includeTableView: false
  maxEntries: 5
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
