columnSuffix: null
handle: tabPanelStyleAdjustments
instructions: null
name: 'Tab Panel Style Adjustments'
searchable: false
settings:
  createButtonLabel: 'Adjust Style'
  entryTypes:
    - 71ab40f6-9c7f-41cc-9887-255aa3c9603a # Style Adjustment - Tab Panel
  includeTableView: false
  maxEntries: 6
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
