columnSuffix: null
handle: videoAsset
instructions: null
name: 'Video Asset'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:7c366b82-7c53-4dd2-a425-1c416a3e1464' # Embeds
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:7c366b82-7c53-4dd2-a425-1c416a3e1464' # Embeds
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:7c366b82-7c53-4dd2-a425-1c416a3e1464' # Embeds
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
