columnSuffix: null
handle: width
instructions: null
name: Width
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (No Change)'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 1/5
        -
          - value
          - 1/5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1/4
        -
          - value
          - 1/4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1/3
        -
          - value
          - 1/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2/5
        -
          - value
          - 2/5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1/2
        -
          - value
          - 1/2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/5
        -
          - value
          - 3/5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2/3
        -
          - value
          - 2/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/4
        -
          - value
          - 3/4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4/5
        -
          - value
          - 4/5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Full Width'
        -
          - value
          - full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
