columnSuffix: null
handle: yesnoYes
instructions: null
name: 'YesNo - Yes'
searchable: false
settings:
  default: true
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
