dateModified: 1714689596
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: 'Page Level Content'
      type: heading
    -
      key: singles
      type: native
    -
      key: 'section:589d7e58-f378-455e-b073-055e9221964b' # Pages
      type: native
    -
      heading: 'Content Elements'
      type: heading
    -
      key: 'section:acec3806-c4ac-4430-a8d9-24915eacc052' # Modals
      type: native
    -
      key: 'section:558fedab-c14e-4f41-a438-ba8c394113a5' # Notification Bar Alerts
      type: native
email:
  fromEmail: brian@tiltthis.com
  fromName: 'Boilermaker 3'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  docs:
    hasUrls: true
    name: Docs
    settings:
      path: $DOC_ASSETS_PATH
    type: craft\fs\Local
    url: $DOC_ASSETS_URL
  embeds:
    hasUrls: true
    name: Embeds
    settings:
      path: $EMBED_ASSETS_PATH
    type: craft\fs\Local
    url: $EMBED_ASSETS_URL
  images:
    hasUrls: true
    name: Images
    settings:
      path: $IMAGE_ASSETS_PATH
    type: craft\fs\Local
    url: $IMAGE_ASSETS_URL
meta:
  __names__:
    0a727c99-d7ce-4920-b1db-ce06d0647067: 'Letter Spacing' # Letter Spacing
    0f72b724-e0a8-4044-a3aa-12255ade6ea1: 'Basic Text with Search' # Basic Text with Search
    0fe2ca3f-eb30-4294-96a2-1154bd95e41e: 'Background Position' # Background Position
    1ef67107-0265-4563-8344-695b0a016e56: Form # Form
    2dc9eeb7-914f-40a8-a177-d21efc54153e: 'Link Settings' # Link Settings
    3aa14a6e-dabc-42ae-8954-e10f19c53441: Accordions # Accordions
    3f041b04-6fce-4165-ab3a-d234dabaa7bd: 'Embed Code' # Embed Code
    3fa40ffc-bcf8-4f2f-9462-19c808265175: 'Multiline Text With Search' # Multiline Text With Search
    4a803a3b-ac9b-4ecc-b439-0815fb18e053: 'Tab Set' # Tab Set
    4c3b1224-ae0a-41b2-b608-0ad42c53ffb5: 'Slider Set' # Slider Set
    4dbe62f4-8253-43b4-9cda-058e34d922c8: Color # Color
    5ad5f513-b34c-48ac-80bf-b573ed1e1f78: 'On Off' # On Off
    5d95a350-fb34-496c-8c66-da3952eb4373: 'Text Alignment' # Text Alignment
    05fecf3b-4603-46ea-9e54-4612defd70e9: 'Layout Row' # Layout Row
    5feec917-01fb-4987-bd1a-c38c337de8cf: Font # Font
    6a43a3aa-97db-498c-b938-2d84a3519729: Pages # Pages
    6b484609-7d28-4f55-990e-f5212885d922: 'Custom ID' # Custom ID
    7c366b82-7c53-4dd2-a425-1c416a3e1464: Embeds # Embeds
    7f182d27-ea6e-4a71-a3f8-5c9d0f147eed: 'Device Size' # Device Size
    9ceecee1-0248-4ae3-a12a-c90171e5f42f: Content # Content
    09d61ba7-f8dd-4e73-bc8f-d580cffbcc1e: 'Boilermaker 3' # Boilermaker 3
    13b06d24-aa17-46e3-89b9-c895a68df851: 'Repeater Display Type' # Repeater Display Type
    37a64193-e3ef-4a2d-aa91-555b436b1d7d: 'Italic?' # Italic?
    40a37d8a-41c1-47af-bc27-28d08f99a909: Slides # Slides
    47acc143-9347-4976-bd50-02778ffeabf1: 'Button Styles' # Button Styles
    51c1b748-da08-41e2-8bd4-b301b9fb6321: 'Column Vertical Alignment' # Column Vertical Alignment
    55cb62d2-f02a-4bd8-849c-695f3a2e92b1: Columns # Columns
    57eb287d-cdc2-4fba-8588-5dc66ff28c86: 'Line Height' # Line Height
    65c293ae-ed92-4c10-b2d3-1251a63c1402: Modal # Modal
    69b9aab4-6d39-462c-b88a-8d4971791897: Simple # Simple
    79d28a86-5f89-45cb-99a4-a97fa0992c73: 'Video Asset' # Video Asset
    82c290d4-2826-4d74-bcc2-8f94ddc4b0b0: 'Accordion Set' # Accordion Set
    82cdb5ee-7722-4897-8e26-fb817c98e85e: Embed # Embed
    91d05e51-ee38-4e73-af4c-ebed7e7572d3: Spacing # Spacing
    93bf7bd8-1004-4c0c-be4d-7b59aa97021e: 'List Order' # List Order
    153c0401-ab92-4149-82ba-2c86f317bc7b: Background # Background
    335fab75-2107-4c96-80b2-14808539eadd: 'Button Group' # Button Group
    400ed272-3701-4004-b0e0-a74db3d25030: Accordion # Accordion
    486d3e65-7880-4e2e-803e-daecc6657a1d: 'Content Wrapper' # Content Wrapper
    558fedab-c14e-4f41-a438-ba8c394113a5: 'Notification Bar Alerts' # Notification Bar Alerts
    589d7e58-f378-455e-b073-055e9221964b: Pages # Pages
    3388d3b4-cb9f-47ee-8874-09e50df3c0bb: 'Section Styling Adjustments' # Section Styling Adjustments
    3710a5c7-fa54-4a2c-a07b-4f7a31f5bd25: 'Background Repeat' # Background Repeat
    8125ecc7-14a0-48fa-beb2-ae316b8c9c0d: 'Entries to List' # Entries to List
    15890ba2-38e4-4bce-9ccc-45ed62101d3e: Section # Section
    93013c2a-acd5-4b87-b999-b352741b10fd: 'Repeater Content' # Repeater Content
    699240f2-b35b-4fad-b00a-f24ec0b8d982: Slide # Slide
    4720320b-f7d0-49ec-a327-0db0e3a2dd7c: 'Slider Size' # Slider Size
    6283122d-7dc0-4b8d-8895-140bc4e66973: 'Page Builder' # Page Builder
    53829185-3375-470c-80cf-a50b1733a8c4: 'Slide Effect' # Slide Effect
    86544431-ce27-4263-b49f-b814ff50fcfb: 'Date Format' # Date Format
    a2da31ae-7341-4dd1-b245-5ee55d44cbc2: 'Yes No' # Yes No
    a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5: 'Custom Classes' # Custom Classes
    acdcfd1c-89a2-4090-989d-17db6ad24060: Icon # Icon
    acec3806-c4ac-4430-a8d9-24915eacc052: Modals # Modals
    ad1fd6cd-1d72-49dd-82fc-6a604b11a71c: 'Icon Content Block' # Icon Content Block
    ad2e8ad9-d9ae-4fee-a8f8-de0e8680707c: Quote # Quote
    adca13f3-4ae5-49c5-83c4-cab3dd9f5ece: 'Button Size' # Button Size
    b1dd9550-b7de-4c8d-ac15-30a80aef59ff: 'Text Case' # Text Case
    b81cc92d-9e5b-440d-8461-cdf9ab64807e: Opacity # Opacity
    b644bda8-1050-46f5-9453-0b3d19812289: Documents # Documents
    b696e4a1-c7cf-4e07-a0be-b9f4f18a2f53: Home # Home
    b6075a2a-820f-44f0-857b-358c60cb2bcb: 'Layout Column' # Layout Column
    ba9877c7-223a-4c59-b461-4cf1a5068a34: 'Font Size' # Font Size
    bae3f95d-8506-49cb-891a-048c975b11d4: 'Heading Level' # Heading Level
    bb8a7c17-de8b-4008-bcca-10c9a30824b5: 'Notification Alerts' # Notification Alerts
    bcc81e37-c9a5-4aaa-a456-847dd36ebf95: CTA # CTA
    c012ee7e-6cb9-4139-803a-2e2dea537718: 'Column Size' # Column Size
    c025e168-6f53-4831-9433-670f03c62851: Buttons # Buttons
    c43e08b0-14a5-4aee-adb4-4e78e9c3d9fe: 'Main Content' # Main Content
    c43e9602-b393-4012-b9c3-c4b391c74cd6: Video # Video
    d1c26bcb-25db-404d-ba73-7e4e3c7fc0a1: 'Slide Transition Delay' # Slide Transition Delay
    d7a280bb-af78-455c-9bd1-1fc2f7e4018d: OpenClosed # OpenClosed
    d85e2e7b-6380-4c46-8ebd-36ad0a2eee46: 'Tab Panel' # Tab Panel
    e2f8e7ee-d666-4bd1-bfe9-ece40a043b3e: Repeater # Repeater
    e6aadd12-c632-4735-b22d-b5a758ab5003: 'Boilermaker 3' # Boilermaker 3
    e2924a45-982c-4a78-8a31-72f8b97462d5: 'Column Order' # Column Order
    e15525d6-6952-4e06-992e-6cf63f053365: Tabs # Tabs
    ee64f702-a8f1-46ee-8dea-79f8ad82e25b: 'Custom Attributes' # Custom Attributes
    f1b466ce-fb41-471a-90d4-5d0fd23f346d: 'Image Asset' # Image Asset
    f4d725e6-48b8-4083-a921-ecc0925a0bff: 'Background Size' # Background Size
    f22d8a3b-9296-4b9a-b338-0d599eaa364a: 'Section to List' # Section to List
    f162c9c9-8174-4ba1-a691-5b2e30f57c37: Root # Root
    fa819c1c-abac-42ac-b1e5-3de37862ccf3: Images # Images
    fd3b49a5-f45c-4fff-9e83-efae0bfb34d4: 'Style Adjustment - Section' # Style Adjustment - Section
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: 73LBUYCONIVXYRPN2X8H1T3P
    schemaVersion: 5.0.0.4
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: ILVR9UKTOZXCUXJHV4EXLPO2
    schemaVersion: 3.4.3
  hyper:
    edition: standard
    enabled: true
    licenseKey: VXB88FJEZGUC74KKXL84U3VP
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: VD3VWGXDBO9AXH1TW54FHKP5
    schemaVersion: 1.2.3
  imager-x:
    edition: pro
    enabled: true
    licenseKey: LHKRYAFYC2VCPJDFU9YPOEVG
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 5V0RT59ZP1JCH3EMCX6R1WO6
    schemaVersion: 2.1.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  retour:
    edition: standard
    enabled: true
    licenseKey: Q4LIRG983QL6LGEMLROAFWAM
    schemaVersion: 3.0.12
  section-and-product-type:
    edition: standard
    enabled: true
    schemaVersion: 2.0.8
  seomatic:
    edition: standard
    enabled: true
    licenseKey: BM5AE9UW4EA5UOEPXXD7L8YI
    schemaVersion: 3.0.12
  shortcodes:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  social-share:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Boilermaker 3'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
