dateModified: 1711493502
email:
  fromEmail: brian@tiltthis.com
  fromName: 'Boilermaker 3'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    09d61ba7-f8dd-4e73-bc8f-d580cffbcc1e: 'Boilermaker 3' # Boilermaker 3
    e6aadd12-c632-4735-b22d-b5a758ab5003: 'Boilermaker 3' # Boilermaker 3
system:
  edition: solo
  live: true
  name: 'Boilermaker 3'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
