dateModified: 1716239935
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: 'Page Level Content'
      type: heading
    -
      key: singles
      type: native
    -
      key: 'section:589d7e58-f378-455e-b073-055e9221964b' # Pages
      type: native
    -
      heading: 'Content Elements'
      type: heading
    -
      key: 'section:acec3806-c4ac-4430-a8d9-24915eacc052' # Modals
      type: native
    -
      key: 'section:558fedab-c14e-4f41-a438-ba8c394113a5' # Notification Bar Alerts
      type: native
email:
  fromEmail: brian@tiltthis.com
  fromName: 'Boilermaker 3'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  docs:
    hasUrls: true
    name: Docs
    settings:
      path: $DOC_ASSETS_PATH
    type: craft\fs\Local
    url: $DOC_ASSETS_URL
  embeds:
    hasUrls: true
    name: Embeds
    settings:
      path: $EMBED_ASSETS_PATH
    type: craft\fs\Local
    url: $EMBED_ASSETS_URL
  mediaUploads:
    hasUrls: true
    name: 'Media Uploads'
    settings:
      path: $MEDIA_UPLOADS_PATH
    type: craft\fs\Local
    url: $MEDIA_UPLOADS_URL
meta:
  __names__:
    0a94a9c4-7b94-408c-919b-9c4a6c070e37: 'Header Block' # Header Block
    0a727c99-d7ce-4920-b1db-ce06d0647067: 'Letter Spacing' # Letter Spacing
    0f72b724-e0a8-4044-a3aa-12255ade6ea1: 'Basic Text with Search' # Basic Text with Search
    0fe2ca3f-eb30-4294-96a2-1154bd95e41e: 'Background Position' # Background Position
    1ef67107-0265-4563-8344-695b0a016e56: Form # Form
    2ac55b2e-329b-4793-af25-3d158c1a4682: 'Accordion Style Adjustments' # Accordion Style Adjustments
    2bf5d5a7-249a-42a4-ae56-79ea7f679bcc: 'Modal to Display' # Modal to Display
    2dc9eeb7-914f-40a8-a177-d21efc54153e: 'Link Settings' # Link Settings
    3aa14a6e-dabc-42ae-8954-e10f19c53441: Accordions # Accordions
    3bcfa1bb-bcae-4957-b813-c81aa2061bfd: 'Text List Style' # Text List Style
    3c147a0d-440a-4850-b41a-98bf61c16df6: Globals # Globals
    3f041b04-6fce-4165-ab3a-d234dabaa7bd: 'Embed Code' # Embed Code
    3fa40ffc-bcf8-4f2f-9462-19c808265175: 'Multiline Text With Search' # Multiline Text With Search
    4a803a3b-ac9b-4ecc-b439-0815fb18e053: 'Tab Set' # Tab Set
    4c3b1224-ae0a-41b2-b608-0ad42c53ffb5: 'Slider Set' # Slider Set
    4ccd8d3b-ddf4-4ac6-89c4-8d344eb6a427: 'Row Style Adjustments' # Row Style Adjustments
    4e9bbb37-55ed-437d-bdbd-9a1dcbc20d73: 'Button Color' # Button Color
    5ad5f513-b34c-48ac-80bf-b573ed1e1f78: 'On Off' # On Off
    5ced14c8-e41a-4186-99ba-01c331a7e430: 'Style Adjustment - Header' # Style Adjustment - Header
    5d95a350-fb34-496c-8c66-da3952eb4373: 'Text Alignment' # Text Alignment
    05fecf3b-4603-46ea-9e54-4612defd70e9: 'Layout Row' # Layout Row
    5feec917-01fb-4987-bd1a-c38c337de8cf: Font # Font
    6a43a3aa-97db-498c-b938-2d84a3519729: Pages # Pages
    6b484609-7d28-4f55-990e-f5212885d922: 'Custom ID' # Custom ID
    6f54afc7-9741-4a74-9500-6ac9ecabb1e9: 'SEO - Robots' # SEO - Robots
    6f85f87f-2394-4346-8cc1-3c89dbc64756: 'Style Adjustment - Row' # Style Adjustment - Row
    7c366b82-7c53-4dd2-a425-1c416a3e1464: Embeds # Embeds
    7f182d27-ea6e-4a71-a3f8-5c9d0f147eed: 'Device Size' # Device Size
    7ff3d23a-91a6-4110-a3b0-b131dd2c3ee3: 'Style Adjustment - Accordion' # Style Adjustment - Accordion
    8cea45ff-f3ed-4c12-b8d2-ed1d8140b912: 'Social Media Links' # Social Media Links
    9cc69c32-6fb9-465d-b7ce-b805d00f5449: 'Row Margins' # Row Margins
    9ceecee1-0248-4ae3-a12a-c90171e5f42f: Content # Content
    09d61ba7-f8dd-4e73-bc8f-d580cffbcc1e: 'Boilermaker 3' # Boilermaker 3
    13b06d24-aa17-46e3-89b9-c895a68df851: 'Repeater Display Type' # Repeater Display Type
    23f01ca6-c4de-4346-a8a1-75a6b95d1f53: 'Form Style Adjustments' # Form Style Adjustments
    37a64193-e3ef-4a2d-aa91-555b436b1d7d: 'Italic?' # Italic?
    37ce7ac2-f596-4d6f-9181-3f4d9fa4d692: 'Block Layout' # Block Layout
    40a37d8a-41c1-47af-bc27-28d08f99a909: Slides # Slides
    47acc143-9347-4976-bd50-02778ffeabf1: 'Button Styles' # Button Styles
    049ec87b-57e9-4b3e-8d53-44cb8874474b: Width # Width
    55cb62d2-f02a-4bd8-849c-695f3a2e92b1: Columns # Columns
    56d80f6e-2a67-464f-af70-0d46d267a0e2: 'Items Per Page' # Items Per Page
    57d8551d-6bb8-45ac-a118-25f3bf7c5b6a: 'Style Adjustment - Repeaters' # Style Adjustment - Repeaters
    57eb287d-cdc2-4fba-8588-5dc66ff28c86: 'Line Height' # Line Height
    62bb1cf0-026e-410e-a685-701783c6ae9e: 'Header Style Adjustments' # Header Style Adjustments
    65c293ae-ed92-4c10-b2d3-1251a63c1402: Modal # Modal
    67dbaf8c-d352-485f-a230-5ba94ad31c07: 'Column Layout' # Column Layout
    69b9aab4-6d39-462c-b88a-8d4971791897: Simple # Simple
    71ab40f6-9c7f-41cc-9887-255aa3c9603a: 'Style Adjustment - Tab Panel' # Style Adjustment - Tab Panel
    073c9d03-dcc0-4435-99fe-2df91703e911: Slide # Slide
    79d28a86-5f89-45cb-99a4-a97fa0992c73: 'Video Asset' # Video Asset
    79fb09c5-0e2c-49d7-bfe6-a9b38820b56a: 'Social Link' # Social Link
    82c290d4-2826-4d74-bcc2-8f94ddc4b0b0: 'Accordion Set' # Accordion Set
    82cdb5ee-7722-4897-8e26-fb817c98e85e: Embed # Embed
    85d1b6aa-228a-4340-bf82-fbdbeec66ee9: 'Icon Style Adjustments' # Icon Style Adjustments
    91d05e51-ee38-4e73-af4c-ebed7e7572d3: Spacing # Spacing
    93bf7bd8-1004-4c0c-be4d-7b59aa97021e: 'List Order' # List Order
    206d3220-640b-4b20-a440-faaa801a11d9: Display # Display
    263e5dea-ef08-42a5-8e17-6418ad4de62b: 'Slide Column' # Slide Column
    335fab75-2107-4c96-80b2-14808539eadd: 'Button Group' # Button Group
    400ed272-3701-4004-b0e0-a74db3d25030: Accordion # Accordion
    413dfe3a-277c-4fba-a7ed-27de63a9a93f: 'Vertical Alignment' # Vertical Alignment
    486d3e65-7880-4e2e-803e-daecc6657a1d: 'Content Wrapper' # Content Wrapper
    487ec441-2218-43e8-8a96-652a0649e437: 'Color Picker' # Color Picker
    524fa6fd-cc9f-4e7a-8791-a28ce1bb3c97: 'Single URL' # Single URL
    554d8669-e659-48d2-a13d-a32598ca78cb: 'Side by Side Photo Style Adjustments' # Side by Side Photo Style Adjustments
    558fedab-c14e-4f41-a438-ba8c394113a5: 'Notification Bar Alerts' # Notification Bar Alerts
    569d975f-7001-40dd-b088-6f9614f17e06: 'Content Wrapper Style Adjustments' # Content Wrapper Style Adjustments
    589d7e58-f378-455e-b073-055e9221964b: Pages # Pages
    732c729f-8dbb-4f01-a463-c163ddc13eab: 'Left Right' # Left Right
    0888a226-1804-4ac8-a00d-8b539fdd3483: '404 Page Content' # 404 Page Content
    938f3198-1925-4908-b0e0-8dfd786c00f1: 'Side by Side Photo Section' # Side by Side Photo Section
    3218b554-b14a-4cc0-8b53-3f4b5b1bcd4c: 'Background Image/Video' # Background Image/Video
    3388d3b4-cb9f-47ee-8874-09e50df3c0bb: 'Section Style Adjustments' # Section Style Adjustments
    3710a5c7-fa54-4a2c-a07b-4f7a31f5bd25: 'Background Repeat' # Background Repeat
    4600cc8f-8e3f-45bf-bbb9-9e48d2e181ed: 'Phone Number' # Phone Number
    5514a63a-0a23-42f9-9333-5576b0e95462: 'Color Scheme' # Color Scheme
    8125ecc7-14a0-48fa-beb2-ae316b8c9c0d: 'Entries to List' # Entries to List
    8186c832-97e2-479b-8fdf-4641f25cf4be: 'Slide Content Layout Row' # Slide Content Layout Row
    15890ba2-38e4-4bce-9ccc-45ed62101d3e: Section # Section
    60656df7-fedd-4651-ae29-cf30fdef7f08: 'Style Adjustment - Slider Set' # Style Adjustment - Slider Set
    68048c93-ca73-447b-9387-512eebe4e90b: 'Slide Columns' # Slide Columns
    93013c2a-acd5-4b87-b999-b352741b10fd: 'Repeater Content' # Repeater Content
    481490a1-1752-4ffc-b455-f05dadea8141: 'Slider Set Style Adjustments' # Slider Set Style Adjustments
    699240f2-b35b-4fad-b00a-f24ec0b8d982: Slide # Slide
    738845b3-b901-49ce-a17b-8a5c7864eab9: 'Content Card' # Content Card
    781363bc-1fd0-4fcc-83b2-80a20c416f57: 'Content Cards' # Content Cards
    03773267-1517-45c4-9a3e-c92f4340a1b2: 'Style Adjustment - CTA' # Style Adjustment - CTA
    4720320b-f7d0-49ec-a327-0db0e3a2dd7c: 'Slider Size' # Slider Size
    6283122d-7dc0-4b8d-8895-140bc4e66973: 'Page Builder' # Page Builder
    13531367-46d6-4c50-8ec6-9bb2a6ab5ab1: 'Number of Columns' # Number of Columns
    31960640-d715-4966-93ba-b66e61df5207: 'Style Adjustment - Accordion Set' # Style Adjustment - Accordion Set
    53829185-3375-470c-80cf-a50b1733a8c4: 'Slide Effect' # Slide Effect
    54321551-57ae-4812-8a1d-c491760d59ad: 'Multi-Column Settings' # Multi-Column Settings
    67336236-2b0e-4d01-bb98-029a923a6932: 'Tab Set Style Adjustments' # Tab Set Style Adjustments
    77532772-badf-4ce5-a93b-6752273d81bb: 'Subhead Position' # Subhead Position
    86544431-ce27-4263-b49f-b814ff50fcfb: 'Date Format' # Date Format
    96056087-af4e-42ba-a559-9152ba279d35: 'Accordion Set Style Adjustments' # Accordion Set Style Adjustments
    a2da31ae-7341-4dd1-b245-5ee55d44cbc2: 'Yes No' # Yes No
    a6e56255-d417-4ac8-9a3f-256c30684cd0: Image # Image
    a7d4ee4f-543c-4209-b4fd-5df98550137d: 'Cards Per Row' # Cards Per Row
    a78e7e89-26cf-4a0e-a36d-b48ca76d7ba5: 'Custom Classes' # Custom Classes
    a547c85e-ce84-4cd3-9a43-5727af411343: 'Style Adjustment - Side by Side Photo Section' # Style Adjustment - Side by Side Photo Section
    acdcfd1c-89a2-4090-989d-17db6ad24060: Icon # Icon
    acec3806-c4ac-4430-a8d9-24915eacc052: Modals # Modals
    ad1fd6cd-1d72-49dd-82fc-6a604b11a71c: 'Icon Content Block' # Icon Content Block
    ad2e8ad9-d9ae-4fee-a8f8-de0e8680707c: Quote # Quote
    adca13f3-4ae5-49c5-83c4-cab3dd9f5ece: 'Button Size' # Button Size
    b1dd9550-b7de-4c8d-ac15-30a80aef59ff: 'Text Case' # Text Case
    b1e1aad8-a87c-4914-9445-bbbbb92076ee: Heading # Heading
    b60b76cf-1ca2-42b6-9ba2-6ad3de0f0e4f: 'Row Layout' # Row Layout
    b81cc92d-9e5b-440d-8461-cdf9ab64807e: Opacity # Opacity
    b352c451-ed85-4679-8a36-8e473facf8a0: 'Style Adjustment - Button Group' # Style Adjustment - Button Group
    b644bda8-1050-46f5-9453-0b3d19812289: Documents # Documents
    b696e4a1-c7cf-4e07-a0be-b9f4f18a2f53: Home # Home
    b6075a2a-820f-44f0-857b-358c60cb2bcb: 'Layout Column' # Layout Column
    b7035329-8f0c-4f1c-985b-104b44d6b235: 'CTA Type' # CTA Type
    ba9877c7-223a-4c59-b461-4cf1a5068a34: 'Font Size' # Font Size
    bae3f95d-8506-49cb-891a-048c975b11d4: 'Heading Level' # Heading Level
    bb8a7c17-de8b-4008-bcca-10c9a30824b5: 'Notification Alerts' # Notification Alerts
    bb89e543-0de1-4a53-9480-2e7c0e8a69a5: 'Aspect Ratio' # Aspect Ratio
    bbe3f16b-50e0-4f6a-9db0-bb6359934f84: 'CTA Style Adjustments' # CTA Style Adjustments
    bcc81e37-c9a5-4aaa-a456-847dd36ebf95: CTA # CTA
    bea4db36-ae23-4382-ad57-5031c47c5ab6: 'Nav List to Display' # Nav List to Display
    c025e168-6f53-4831-9433-670f03c62851: Buttons # Buttons
    c3d75796-b930-48a0-b387-b5469be4094b: 'Full Listing Button' # Full Listing Button
    c9cf2b48-b578-41dd-ae7f-82d0ce5a4241: 'Image/Video Style Adjustments' # Image/Video Style Adjustments
    c43e08b0-14a5-4aee-adb4-4e78e9c3d9fe: 'Main Content' # Main Content
    c43e9602-b393-4012-b9c3-c4b391c74cd6: Video # Video
    cc44dfc3-f9d6-4fcc-9940-621e8a3981f0: 'Quote Style Adjustments' # Quote Style Adjustments
    d1c26bcb-25db-404d-ba73-7e4e3c7fc0a1: 'Slide Transition Delay' # Slide Transition Delay
    d7a280bb-af78-455c-9bd1-1fc2f7e4018d: OpenClosed # OpenClosed
    d7b08a46-def6-44b3-9d7d-4ef745756fca: 'Style Adjustment - Slide' # Style Adjustment - Slide
    d50bf5e2-cf37-49d5-99dc-0f5fe25e5121: Background # Background
    d85e2e7b-6380-4c46-8ebd-36ad0a2eee46: 'Tab Panel' # Tab Panel
    d897b42d-3d26-4db5-b105-29c871b31ffb: 'Slide Content' # Slide Content
    d81788e7-2fa5-4804-876d-57de4924e46f: 'Style Adjustment - Icon' # Style Adjustment - Icon
    dd25301d-9012-41dd-aa43-19f023540545: 'Button Group Style Adjustment' # Button Group Style Adjustment
    ddb8108e-63a9-4567-80ba-7ab621baad89: 'Style Adjustment - Quote' # Style Adjustment - Quote
    de6881eb-f48b-4119-889c-95d3bf6692e5: 'Style Adjustment - Tab Set' # Style Adjustment - Tab Set
    e2f8e7ee-d666-4bd1-bfe9-ece40a043b3e: Repeater # Repeater
    e3f9e59c-e941-404e-8bc8-b4c57ff28d5c: 'YesNo - Yes' # YesNo - Yes
    e6aadd12-c632-4735-b22d-b5a758ab5003: 'Boilermaker 3' # Boilermaker 3
    e8d249f8-2c18-4b51-b311-baabbd94f999: 'Style Adjustment - Image/Video' # Style Adjustment - Image/Video
    e15525d6-6952-4e06-992e-6cf63f053365: Tabs # Tabs
    e5542413-6c20-435f-8598-e457fb2d1a50: 'Page Header Background' # Page Header Background
    ea38d6d4-055b-43b8-b876-2bcab46e11c8: 'Company Info' # Company Info
    ecb5f699-34c7-440c-bb60-a045e0e28b18: 'Slide Style Adjustments' # Slide Style Adjustments
    ee6d1ced-9ba0-4c31-9f10-d3e6057ae634: 'Style Adjustment - Column' # Style Adjustment - Column
    ee64f702-a8f1-46ee-8dea-79f8ad82e25b: 'Custom Attributes' # Custom Attributes
    f0c10f75-8d5e-43c0-83a1-2321c04a2ebd: 'Form to Display' # Form to Display
    f1b466ce-fb41-471a-90d4-5d0fd23f346d: 'Image Asset' # Image Asset
    f4d725e6-48b8-4083-a921-ecc0925a0bff: 'Background Size' # Background Size
    f7dc9df7-f17d-4c82-9b2e-2bd2986c309f: 'Column Style Adjustments' # Column Style Adjustments
    f13a58c0-cc0e-41c6-b75b-f014f8de92a6: 'Tab Panel Style Adjustments' # Tab Panel Style Adjustments
    f22d8a3b-9296-4b9a-b338-0d599eaa364a: 'Section to List' # Section to List
    f103b592-617a-4840-8a3b-ce98a171eb09: 'Style Adjustment - Content Wrapper' # Style Adjustment - Content Wrapper
    f162c9c9-8174-4ba1-a691-5b2e30f57c37: Root # Root
    f7399346-9a4c-44e7-99c4-ca44c88fbb0f: 'Content Links' # Content Links
    fa819c1c-abac-42ac-b1e5-3de37862ccf3: Media # Media
    fd3b49a5-f45c-4fff-9e83-efae0bfb34d4: 'Style Adjustment - Section' # Style Adjustment - Section
    fdc69893-7848-4bd4-8f1d-3df385771a84: 'Repeater Style Adjustments' # Repeater Style Adjustments
    fe981b00-296b-4916-816f-a8e2670638e3: 'Style Adjustment - Form' # Style Adjustment - Form
    ff110645-b126-49e5-9ed9-a720a1a9d3d2: 'Notification Bar Color' # Notification Bar Color
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: 73LBUYCONIVXYRPN2X8H1T3P
    schemaVersion: 5.0.0.4
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: ILVR9UKTOZXCUXJHV4EXLPO2
    schemaVersion: 3.4.3
  hyper:
    edition: standard
    enabled: true
    licenseKey: VXB88FJEZGUC74KKXL84U3VP
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: VD3VWGXDBO9AXH1TW54FHKP5
    schemaVersion: 1.2.3
  imager-x:
    edition: pro
    enabled: true
    licenseKey: LHKRYAFYC2VCPJDFU9YPOEVG
    schemaVersion: 4.0.0
  imager-x-power-pack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 5V0RT59ZP1JCH3EMCX6R1WO6
    schemaVersion: 2.1.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  retour:
    edition: standard
    enabled: true
    licenseKey: Q4LIRG983QL6LGEMLROAFWAM
    schemaVersion: 3.0.12
  section-and-product-type:
    edition: standard
    enabled: true
    schemaVersion: 2.0.8
  seomatic:
    edition: standard
    enabled: true
    licenseKey: BM5AE9UW4EA5UOEPXXD7L8YI
    schemaVersion: 3.0.12
  shortcodes:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  social-share:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Boilermaker 3'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
