fieldLayouts:
  3e4d980a-483a-401c-8073-0cc15c5b0d92:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4600cc8f-8e3f-45bf-bbb9-9e48d2e181ed # Phone Number
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbb16876-e504-4b25-a085-4f2069885ebc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8cea45ff-f3ed-4c12-b8d2-ed1d8140b912 # Social Media Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 069fcaea-20e9-42bd-90a6-78b556c7df4d
            userCondition: null
            warning: null
            width: 100
        name: 'Company Info'
        uid: dafac861-0cd9-4e71-b606-1ced52de55d2
        userCondition: null
handle: companyInfo
name: 'Company Info'
sortOrder: 1
