fieldLayouts:
  c9d96308-6e2e-46e4-82b0-7f4eb9481184:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6283122d-7dc0-4b8d-8895-140bc4e66973 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3040cfc0-67e2-453f-a909-57e8f6442a94
            userCondition: null
            warning: null
            width: 100
        name: '404 Page Content'
        uid: 64d093fe-4a7f-457e-90a0-7387a8820175
        userCondition: null
handle: page404
name: '404 Page Content'
sortOrder: 2
